"""Canonical Document IR public contract."""

from docparser.ir.chunks import (
    Chunk,
    ChunkBBox,
    GlobalReferenceEntry,
    IRPackagingManifest,
    IRShardDescriptor,
)
from docparser.ir.content import (
    Equation,
    Figure,
    IssueCounts,
    QualitySummary,
    ReferenceEntry,
    Section,
)
from docparser.ir.enums import (
    BlockType,
    ChunkType,
    ConfidenceSource,
    Determinism,
    EquationFormat,
    ExtractionMethod,
    IRShardKind,
    QualityStatus,
    ReadingOrderStatus,
    RelationshipType,
    TextDirection,
)
from docparser.ir.fingerprints import semantic_fingerprint
from docparser.ir.geometry import AffineTransform, BBox, PageGeometry, Point, Rotation
from docparser.ir.ids import (
    ArtifactId,
    BlockId,
    ChunkId,
    DocumentId,
    EquationId,
    FigureId,
    PageId,
    ParserRunId,
    ProvenanceId,
    QualityReportId,
    ReferenceId,
    RelationshipId,
    RevisionId,
    RevisionIdGenerator,
    SectionId,
    TableCellId,
    TableId,
    TableSegmentId,
    generate_document_id,
    generate_page_id,
    generate_uuid5_id,
)
from docparser.ir.invariants import resolve_heading_path, validate_document_invariants
from docparser.ir.migrations import migrate_ir
from docparser.ir.models import (
    Block,
    DocumentIR,
    Page,
    ProcessingManifest,
    ProvenanceRecord,
    SourceDocument,
    TextSpan,
)
from docparser.ir.relationships import Relationship
from docparser.ir.serialization import (
    dump_canonical_json,
    load_canonical_json,
    semantic_digest,
    validate_ir,
)
from docparser.ir.tables import Table, TableCell, TableCellFragment, TableSegment

__all__ = [
    "AffineTransform",
    "ArtifactId",
    "BBox",
    "Block",
    "BlockId",
    "BlockType",
    "Chunk",
    "ChunkBBox",
    "ChunkId",
    "ChunkType",
    "ConfidenceSource",
    "Determinism",
    "DocumentIR",
    "DocumentId",
    "Equation",
    "EquationFormat",
    "EquationId",
    "ExtractionMethod",
    "Figure",
    "FigureId",
    "GlobalReferenceEntry",
    "IRPackagingManifest",
    "IRShardDescriptor",
    "IRShardKind",
    "IssueCounts",
    "Page",
    "PageGeometry",
    "PageId",
    "ParserRunId",
    "Point",
    "ProcessingManifest",
    "ProvenanceId",
    "ProvenanceRecord",
    "QualityReportId",
    "QualityStatus",
    "QualitySummary",
    "ReadingOrderStatus",
    "ReferenceEntry",
    "ReferenceId",
    "Relationship",
    "RelationshipId",
    "RelationshipType",
    "RevisionId",
    "RevisionIdGenerator",
    "Rotation",
    "Section",
    "SectionId",
    "SourceDocument",
    "TextDirection",
    "TextSpan",
    "Table",
    "TableCell",
    "TableCellFragment",
    "TableCellId",
    "TableId",
    "TableSegment",
    "TableSegmentId",
    "dump_canonical_json",
    "generate_document_id",
    "generate_page_id",
    "generate_uuid5_id",
    "load_canonical_json",
    "migrate_ir",
    "resolve_heading_path",
    "semantic_digest",
    "semantic_fingerprint",
    "validate_ir",
    "validate_document_invariants",
]
