"""Canonical Document IR public contract."""

from docparser.ir.geometry import AffineTransform, BBox, PageGeometry, Point, Rotation
from docparser.ir.ids import (
    ArtifactId,
    BlockId,
    DocumentId,
    PageId,
    ParserRunId,
    ProvenanceId,
    RevisionId,
    RevisionIdGenerator,
    generate_document_id,
    generate_page_id,
    generate_uuid5_id,
)
from docparser.ir.models import (
    Block,
    BlockType,
    ConfidenceSource,
    Determinism,
    DocumentIR,
    ExtractionMethod,
    Page,
    ProcessingManifest,
    ProvenanceRecord,
    ReadingOrderStatus,
    SourceDocument,
    TextDirection,
    TextSpan,
)
from docparser.ir.serialization import (
    dump_canonical_json,
    load_canonical_json,
    semantic_digest,
    validate_ir,
)

__all__ = [
    "AffineTransform",
    "ArtifactId",
    "BBox",
    "Block",
    "BlockId",
    "BlockType",
    "ConfidenceSource",
    "Determinism",
    "DocumentIR",
    "DocumentId",
    "ExtractionMethod",
    "Page",
    "PageGeometry",
    "PageId",
    "ParserRunId",
    "Point",
    "ProcessingManifest",
    "ProvenanceId",
    "ProvenanceRecord",
    "ReadingOrderStatus",
    "RevisionId",
    "RevisionIdGenerator",
    "Rotation",
    "SourceDocument",
    "TextDirection",
    "TextSpan",
    "dump_canonical_json",
    "generate_document_id",
    "generate_page_id",
    "generate_uuid5_id",
    "load_canonical_json",
    "semantic_digest",
    "validate_ir",
]
