"""Public Quality Gate API."""

from docparser.quality.calibration import (
    calibration_report_digest,
    decision_for_scope,
    evaluate_calibration,
    failure_label_matches_signal,
    freeze_profile,
)
from docparser.quality.engine import (
    QUALITY_RULESET_VERSION,
    DeterministicQualityGate,
    apply_quality_report,
)
from docparser.quality.models import (
    AcceptanceUnit,
    CalibrationProfile,
    CalibrationReport,
    CalibrationSample,
    CalibrationTargetTruth,
    CalibrationTruth,
    CompletenessThresholds,
    FailureLabel,
    QualityDecision,
    QualityMode,
    QualityReport,
    QualityScope,
    QualitySignal,
    QualityTarget,
    RuleAction,
    SignalOutcome,
    TableThresholds,
    ValidationRequest,
    quality_mode_for_request,
)

__all__ = [
    "QUALITY_RULESET_VERSION",
    "AcceptanceUnit",
    "CalibrationProfile",
    "CalibrationReport",
    "CalibrationSample",
    "CalibrationTargetTruth",
    "CalibrationTruth",
    "CompletenessThresholds",
    "DeterministicQualityGate",
    "FailureLabel",
    "QualityDecision",
    "QualityMode",
    "QualityReport",
    "QualityScope",
    "QualitySignal",
    "QualityTarget",
    "RuleAction",
    "SignalOutcome",
    "TableThresholds",
    "ValidationRequest",
    "apply_quality_report",
    "calibration_report_digest",
    "decision_for_scope",
    "evaluate_calibration",
    "failure_label_matches_signal",
    "freeze_profile",
    "quality_mode_for_request",
]
